version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file: ../../config/env/development.env 
    volumes:
      - redisdb:/data
    networks:
      - redis

volumes:
  redisdb:

networks:
  redis:
    driver: bridge